### ISSUE TITLE
Convert px to em

### ISSUE THREAD

**Issue by geoff-maddock** [geoff-maddock/events-tracker#737]
Catalog  places I'm using px and convert to em or rem unless there's a reason

**Comment by SachinCoder1** [comment]
Hi, is anyone working on it? i am new to open source, how do i get started?

**Comment by geoff-maddock** [comment]
Thanks for the interest @SachinCoder1 - are you running a copy of the code?   Overall I think this issue needs to be groomed more before I could have somebody work on it.

**Comment by geoff-maddock** [comment]
Looked over everything in resources/views.  Should be good for now.
